eval$s=%w(s=%(eval$s=%w(#{$s})*"");f=->n{s.sl
ice!(0,n)};a=[7,116];b=[6,1,116,1];c=[0,1,128
,1];d='oxVw';e='~}]y{y|{}}}}}}}}}}|}}}}}}}}}}
{|y{yY}';g=['vA','u@','tA','syNy',*[[]]*7,'|3
','{3','z4','ymRs','wwGy',*[[]]*4];h='~}^y|v|
r|r|v|yZ}@~}_y|v}}|ypy|}}v|y[}@~}_z|v}{d{}v|z
[}@~}`z{w}zyy}z}yyz}w{z\}@~}ay|w}zyy}x}yyz}w|
y]}@~}az{w}z{x}v}x{z}w{z]}@~}azzx}|z|}}}}}t}}
}}}|z|}xzz]}@~}azky}v}ykz]}@~}azzx}|vz}x}zv|}
xzz]}@~}az{w}zv{}z}{vz}w{z]}@~}ay|w}zt|}|}|tz
}w|y]}@~}`z{w}zszsz}w{z\}@~}_z|v}{r|r{}v|z[}@
~}_y|v}}|ypy|}}v|y[}@~}^y|v|r|r|v|yZ}'.split(
'@');i='~}{vp|m|z{`wxzxw|uz}@~}{|y{r|m|{{a|zz
{{|{|{z{}|s}@~}{|y{r|m|||o|t|||y{|{z{}|y{}|}y
y}@~}{vpxqyxwvxs{{{z{w{|{|zz}@~}{{{{z|||{|{||
|z|||||z|z|{|||{|}|yzy{z{zzt{z}@~}{{z{{|||{|{
|{|||{|{{||z|{|||{|}|{zv{|{{zx|z{z}@~}{{y{|w|
yxzz|z{|y|}||{x}||tzx{t|wy}@~}Y|[|J}@~}Z|_|{|
J}@~}[|\zI}@~}I{y|b{yyf}@~}p|i|||uzz|q|qzz|{|
v|q}@~}qzq}t|s|zxy|||o|yyy|||q}@}}s|||zx|y|||
|s|z|{|{z}y|yy|z|{|{z}yu}@|}uv{|{|}|y|||s|z|{
|z|||}|r|z|{|z|||}|v}@{}w|x||x||y|||ux{yy|||}
|tx{yy|||}|w}@z}l|R}G}@y}m|R}H}'.split('@');j
='@x%vA%uA%tA%sykw%[w%]w%]x%^x%_xmz%lR%iS%awm
u%bwlw%bwlx%cwkx%cwky%dwjy%ewiy%ewjx%fwix%gwh
x%gwiv%|3%{3%z3%ytLs'.split('%');l1='picoairX
@sbjigbvX@v]pan]xx@xrrqtxixrrrqzx@zslryxdxvsl
r|x@{ufuyxdxwufu|x@|tfu{vcv{tfu|x@}ucv{vcv|uc
v|xwk@}wav{vcv|wav|xze@}wbu{vcv|wbu|X@}wbu{vc
v|wbu|mvo@}wct{vcv|wct|prp@\tzvcv[t{rnr@]tyvc
v\t^r@`tvvcv_tZs@cstvcvbsXs@fsqvcvesUs@jsmvcv
isQs@msjvcvlsNs@psgvcvosKs@rtdvcvqtHs@uu`vcvt
uEr@wt]xcxttDr@zs[xcxws^qpq@{sXxgxvs[rro@}Tsa
uSyZ@}SoiqSw^@}SlonSrf'.split('@');l2=[*g,'d`
','hY','jS','lu`v','mw\v','nwYw','owWw','owWw
',*[d]*5,'owWw','owWx','nwZw','mw\w','juet','
hW','c_',*[[]]*4,*g,*j];l3=[a,b,'y}OjK}','z}T
o|nQ}','{}VujuR}','|}XwyvzvywT}','}}Yxzq|qzxU
}','~}Zxyp|pyxV}','~}[y{||p|p||{yW}',e,*h,e,'
~}[y{||p|p||{yW}','~}Zxyp|pyxV}','~}Xxzq|qzxT
}','~}VwyvzvywR}','~}SujuO}','~}Po|nM}','~}Jj
F}',c,c,*i,b,a];l={'Number'=>l1,'Kanji'=>l2,'
RubyKaigi'=>l3}[ARGV[0]];l.map{|l|l.is_a?(Str
ing)?l.bytes.map{126-_1}:l}.each{|l|puts(l.ea
ch_slice(2).map{|x,y|"\s"*x+f[y]}.join)};)*""
