                                            eval(
                                          %w(e,hi                          
                                       me,k='愛媛県'                          
                                    .split('').ma                          
                                  p(&:ord);;b=k.t                          
                                 o_s.split('').m                           
                                 ap(&:to_i).sum                            
                         ;;u=(e.to_s.split('').map(&:                      
                    to_i).sum-b);;t=(e.to_s.split('').ma                   
                p(&:to_i).sum%u+((k-e)/(b*b)%u));;g=(t*t);;                
              ;c=[[(hime>>u),e.to_s.split('').map(&:to_i).sum]             
           .sum-t,g].sum;;;d=(k>>u);;i=(e>>u);;n=hime.to_s.split           
         ('')[..(hime.to_s.split('').map(&:to_i).sum/b)].join.to_i         
       ;;o=(hime>>t);;r=((b/(e.to_s.split('').map(&:to_i).sum%u))*(        
      e.to_s.split('').map(&:to_i).sum/u));;v=(u*((k-e)/(b*b))>>(e.to      
     _s.split('').map(&:to_i).sum%u));;send([(u*((k-e)/(b*b))).chr,((      
    e.to_s.split('').map(&:to_i).sum/u)*(e.to_s.split('').map(&:to_i).s    
   um/u)*((e.to_s.split('').map(&:to_i).sum/u)+t)).chr,((e.to_s.split('    
  ').map(&:to_i).sum%u)*(b+(e.to_s.split('').map(&:to_i).sum/u)*(e.to_s.   
  split('').map(&:to_i).sum/u))).chr,((b/(e.to_s.split('').map(&:to_i).s   
 um%u))*(b+(e.to_s.split('').map(&:to_i).sum/u))).chr,].join,[(u*((b/(e.t  
 o_s.split('').map(&:to_i).sum%u))+(e.to_s.split('').map(&:to_i).sum%u)))  
 .chr,(i+((e.to_s.split('').map(&:to_i).sum%u))).chr,([(hime>>u),e.to_s.s  
 plit('').map(&:to_i).sum].sum-t).chr,([(hime>>u),e.to_s.split('').map(&:  
 to_i).sum].sum-t).chr,(d-u).chr,(e.to_s.split('').map(&:to_i).sum+(b/(e.  
 to_s.split('').map(&:to_i).sum%u))).chr,([o,t].sum).chr,(n*(e.to_s.split  
 ('').map(&:to_i).sum/u)).chr,(c>>(hime.to_s.split('').map(&:to_i).sum/b   
  )).chr,(r*v).chr,((k.to_s.split('').delete_if{it.to_i<(e.to_s.split(''   
   ).map(&:to_i).sum%((e.to_s.split('').map(&:to_i).sum-b)))}.then(&:jo    
   in).to_i-t*(e.to_s.split('').map(&:to_i).sum%u))>>(o%hime.to_s.spli     
    t('').map(&:to_i).sum)).chr,(i+((e.to_s.split('').map(&:to_i).sum%     
     u))).chr,([k.to_s.split('').delete_if{it.to_i<(e.to_s.split('').      
      map(&:to_i).sum%((e.to_s.split('').map(&:to_i).sum-b)))}.then        
       (&:join).to_i+e.to_s.split('').map(&:to_i).sum+o].sum*((k.t         
         o_s.split('').delete_if{it.to_i<(e.to_s.split('').map(&           
            :to_i).sum%((e.to_s.split('').map(&:to_i).sum-b)))             
               }.then(&:join).to_i+t)>>(hime.to_s.split('')                
                   .map(&:to_i).sum/b))).chr(eval("Encod                   
                        ing::UTF_#{u}"))].join))*"")                       
